# Generated by Django 2.2.6 on 2020-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=5)),
                ('term', models.CharField(max_length=10)),
                ('klass', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=10)),
            ],
        ),
    ]
