# Generated by Django 2.2.6 on 2020-04-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marklist',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MarkListSetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_papers', models.BooleanField(default=False)),
                ('num_exams', models.IntegerField()),
                ('marklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportcards.MarkList')),
            ],
        ),
    ]
