# Generated by Django 2.2.6 on 2020-04-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0003_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
