# Generated by Django 2.2.6 on 2020-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0009_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
