# Generated by Django 2.2.6 on 2020-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sir_name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=8)),
                ('klass', models.CharField(choices=[('S.1', 'S.1'), ('S.2', 'S.2'), ('S.3', 'S.3'), ('S.4', 'S.4'), ('S.5', 'S.5'), ('S.6', 'S.6')], max_length=5)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S')], max_length=10)),
            ],
        ),
    ]
