# Generated by Django 2.2.6 on 2020-04-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200403_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
