# Generated by Django 2.2.6 on 2020-04-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='papers',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
