# Generated by Django 2.2.6 on 2020-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_paper_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_compulsary',
            field=models.BooleanField(default=False),
        ),
    ]
