# Generated by Django 2.2.6 on 2020-04-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_subject_is_compulsary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
