# Generated by Django 2.2.6 on 2020-04-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0013_auto_20200404_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=6)),
                ('alevel', models.BooleanField()),
                ('olevel', models.BooleanField()),
                ('olevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('alevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_compulsary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('level', models.CharField(choices=[('Alevel', 'Alevel'), ('Olevel', 'Olevel')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject')),
            ],
        ),
    ]
