# Generated by Django 2.2.6 on 2020-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0016_auto_20200406_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=6)),
                ('alevel', models.BooleanField()),
                ('olevel', models.BooleanField()),
                ('olevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('alevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_compulsary', models.BooleanField(default=False)),
            ],
        ),
    ]
