# Generated by Django 2.2.6 on 2020-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=(), to='students.Subject'),
        ),
    ]
