# Generated by Django 2.2.6 on 2020-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200406_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=(), to='students.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='alevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='olevel',
            field=models.BooleanField(default=False),
        ),
    ]
