# Generated by Django 2.2.6 on 2020-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20200408_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=(), to='students.Subject'),
        ),
    ]
