# Generated by Django 2.2.6 on 2020-04-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20200411_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=(), to='students.Subject'),
        ),
    ]
