# Generated by Django 2.2.6 on 2020-04-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20200413_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
