# Generated by Django 3.0.5 on 2020-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fro_date', models.DateField()),
                ('fro_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
