# Generated by Django 3.0.5 on 2020-04-29 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200429_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fro_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
