# Generated by Django 3.0.5 on 2020-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200429_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fro_date',
            field=models.DateField(),
        ),
    ]
