# Generated by Django 3.0.5 on 2020-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200429_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
