# Generated by Django 3.0.5 on 2020-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200429_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Event')),
                ('year', models.IntegerField()),
            ],
            bases=('mainapp.event',),
        ),
    ]
